# Generated by Django 5.0 on 2023-12-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bio', models.TextField()),
                ('twitter_link', models.CharField(max_length=155)),
                ('instagram_link', models.CharField(max_length=155)),
                ('facebook_link', models.CharField(max_length=155)),
                ('telegram_link', models.CharField(max_length=155)),
                ('pinterest_link', models.CharField(max_length=155)),
                ('follows', models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='user_profile.userprofile')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
