# Generated by Django 5.0 on 2024-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_name_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='user_profile.userprofile'),
        ),
    ]
