# Generated by Django 5.0.1 on 2024-01-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
