# Generated by Django 5.0.1 on 2024-01-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='created_by',
        ),
    ]
